# Generated by Django 4.1.5 on 2023-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('PN', 'Panner'), ('CZ', 'Cheese'), ('IC', 'ice-Creams')], max_length=2),
        ),
    ]
